# Generated by Django 4.2.2 on 2023-06-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitflexx', '0003_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='class_item',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
